import * as go from 'gojs';

export const FLOOR_CONTAINER_KEY = 'FLOOR_CONTAINER_KEY';
export const FLOOR_CONTAINER_NAME = 'FLOOR_CONTAINER_NAME';
export const FLOOR_CONTAINER_BORDERS_NAME = 'FLOOR_CONTAINER_BORDERS_NAME';
export const ALLOW_DROP_OUTSIDE_HIGHLIGHTED_AREA = false;
export const CELL_SIZE = new go.Size(20, 20);
