
/**
 * AUTO-GENERATED FILE @ Fri, 14 Jun 2024 20:16:05 GMT - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.1.0.8
 * $ schemats generate postgres://username:password@desk-bookin.cnm26saq6c27.eu-central-1.rds.amazonaws.com:5432/desk_booking -s public
 *
 */



export interface buildings { 
  id: string
  name: string
  user_id: string 
}

export interface bookings { 
  id: string
  interval: any
  office_id: string
  user_id: string 
}

export interface offices { 
  id: string
  name: string
  x: number
  y: number
  floor_id: string 
}

export interface office_ratings { 
  id: string
  stars: number
  reviewer_id: string
  office_id: string 
}

export interface floors { 
  id: string
  level: number
  building_id: string 
}

export interface users { 
  id: string
  name: string
  email: string
  password: string
  admin: boolean 
}

export interface building_ratings { 
  id: string
  stars: number
  reviewer_id: string
  building_id: string
  deleted?: boolean | null 
}

export interface unverified_bookings { 
  id: string
  interval: any
  office_id: string
  user_id: string 
}

export interface building_rating_updates { 
  id: string
  stars: number
  reviewer_id: string
  building_id: string
  updated_at?: Date | null
  deleted?: boolean | null 
}

export interface Tables {
  buildings: buildings,
  bookings: bookings,
  offices: offices,
  office_ratings: office_ratings,
  floors: floors,
  users: users,
  building_ratings: building_ratings,
  unverified_bookings: unverified_bookings,
  building_rating_updates: building_rating_updates
}